// Builds styles/icons.min.css (icon shapes, loaded async) and the icon sizing block in styles.css/styles.min.css.
// Run from the repo root after using a new icon: node tools/build-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

const FA = 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.0';
const STYLE = { fa: 'solid', fas: 'solid', 'fa-solid': 'solid', far: 'regular', 'fa-regular': 'regular', fab: 'brands', 'fa-brands': 'brands' };
const MODIFIERS = new Set(['fa-fw', 'fa-lg', 'fa-xs', 'fa-sm', 'fa-1x', 'fa-2x', 'fa-3x', 'fa-spin', 'fa-pulse']);
// Class names assembled in page scripts (horoscope, panchang, rahu-kaal, dasha-calculator), which the scan can't see
const FROM_JS = {
  solid: ['briefcase', 'wallet', 'heart', 'spa', 'sun', 'moon', 'clock', 'star', 'circle', 'check-circle', 'exclamation-triangle', 'info-circle'],
  brands: ['google-play', 'apple'],
};

const used = new Map();
for (const [style, names] of Object.entries(FROM_JS)) for (const n of names) used.set(n, style);
const pages = execSync("git ls-files -co --exclude-standard -- '*.html' ':!docs'").toString().trim().split('\n');
for (const file of pages) {
  for (const [, cls] of readFileSync(file, 'utf8').matchAll(/class="([^"]*)"/g)) {
    const toks = cls.split(/\s+/);
    const style = toks.map((t) => STYLE[t]).find(Boolean);
    if (!style) continue;
    for (const t of toks) {
      if (!/^fa-[a-z0-9-]+$/.test(t) || STYLE[t] || MODIFIERS.has(t)) continue;
      const name = t.slice(3);
      if (used.has(name) && used.get(name) !== style) throw new Error(`fa-${name} is used as both ${used.get(name)} and ${style}`);
      used.set(name, style);
    }
  }
}

const meta = await (await fetch(`${FA}/metadata/icon-families.json`)).json();
const alias = {};
for (const [name, m] of Object.entries(meta)) for (const a of m.aliases?.names ?? []) alias[a] = name;

const esc = (s) => s.replace(/%/g, '%25').replace(/</g, '%3C').replace(/>/g, '%3E').replace(/#/g, '%23').replace(/"/g, '%22');
const em = (w, h) => `${String(+(w / h).toFixed(4)).replace(/^0\./, '.')}em`;
const widths = new Map();
const shapes = [];
const missing = [];
for (const [name, style] of [...used].sort()) {
  const svg = meta[meta[name] ? name : alias[name]]?.svgs?.classic?.[style];
  if (!svg) {
    missing.push(`${style}/${name}`);
    continue;
  }
  const [, , w, h] = svg.viewBox;
  const sel = `.fa-${name}::before`;
  const width = em(w, h);
  widths.set(width, [...(widths.get(width) ?? []), sel]);
  shapes.push(`${sel}{--fa-i:url("data:image/svg+xml,${esc(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${w} ${h}'><path d='${svg.path}'/></svg>`)}")}`);
}

const block = [
  '/* icons:start - generated by tools/build-icons.mjs */',
  '.fa,.fas,.far,.fab{display:inline-block;font-style:normal;line-height:0}',
  '.fa::before,.fas::before,.far::before,.fab::before{display:inline-block;height:1em;vertical-align:-.125em}',
  '.fa-2x{font-size:2em}',
  ...[...widths].map(([width, sels]) => `${sels.join(',')}{content:"";width:${width}}`),
  '/* icons:end */',
];
for (const file of ['styles/styles.css', 'styles/styles.min.css']) {
  const css = readFileSync(file, 'utf8');
  const markers = /\/\* icons:start[^]*?\/\* icons:end \*\//;
  if (!markers.test(css)) throw new Error(`${file}: icons:start/icons:end markers not found`);
  writeFileSync(file, css.replace(markers, () => block.join(file.endsWith('.min.css') ? '' : '\n')));
}

writeFileSync('styles/icons.min.css', [
  '/*! Icons: Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0) */',
  '.fa::before,.fas::before,.far::before,.fab::before{background-color:currentColor;-webkit-mask:var(--fa-i) center/contain no-repeat;mask:var(--fa-i) center/contain no-repeat}',
  '.fa-spin{animation:fa-spin 2s linear infinite}',
  '@keyframes fa-spin{to{transform:rotate(1turn)}}',
  '@media (prefers-reduced-motion:reduce){.fa-spin{animation:none}}',
  ...shapes,
].join('\n') + '\n');

console.log(`${shapes.length} icons written${missing.length ? `; not in Font Awesome Free (left blank): ${missing.join(', ')}` : ''}`);
console.log('Bump ?v= on styles.min.css and icons.min.css links if either changed.');
